manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 3200,  d: 200, i: -0.05, i_clamp: 100}
    shoulder_lift_joint: {p: 15000,  d: 800, i: 30, i_clamp: 200}
    elbow_joint: {p: 10000,  d: 50, i: 0.01, i_clamp: 10}
    wrist_1_joint: {p: 500,  d: 20, i: 1, i_clamp: 10}
    wrist_2_joint: {p: 100,  d: 10, i: 0.1, i_clamp: 5}
    wrist_3_joint: {p: 100,  d: 0.5, i: 0.1, i_clamp: 100} 
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.01
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.01}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.01}
    elbow_joint: {trajectory: 0.1, goal: 0.01}
    wrist_1_joint: {trajectory: 0.01, goal: 0.01}
    wrist_2_joint: {trajectory: 0.01, goal: 0.01}
    wrist_3_joint: {trajectory: 0.01, goal: 0.01}
  stop_trajectory_duration: 0.5
  state_publish_rate: 250
  action_monitor_rate: 50
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint
  gains:
    robotiq_85_left_knuckle_joint:
      p: 30
      d: 0
      i: 0
      i_clamp: 1